#!/usr/bin/env python3
"""
master_refit_audit.py -- clean-room raw -> drive_master reproducibility audit
(audit 2026-09-17 follow-up, M285).

Rebuilds the per-drive master from the raw CSVs with the versioned core builder
(compute_drive_summary_v6: analyze_bytes -> postprocess_master, i.e. exactly what
build_master_from_raw does, row-parallelised) and compares it column-by-column with
the PUBLISHED drive_master.csv. It never writes drive_master.csv.

Emits the `masterRefitAudit` block (JSON) consumed by the dashboard reproducibility
prose, so the "what reproduces / what does not" statement is measured, not asserted.

Classification of each column:
  identical   -- same null pattern and |diff| <= 1e-9 on every row
  drifted     -- differs on >=1 row (count, max |diff| and null-pattern mismatches reported)

Usage:
  XT_RAW=/path/to/raw python3 master_refit_audit.py PUBLISHED_MASTER.csv OUT.json [--workers 2]
"""
import sys, os, glob, json, time, datetime, hashlib, platform
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.environ.get('XT_CODE', HERE))
import compute_drive_summary_v6 as v6

RAW = os.environ.get('XT_RAW', '/mnt/project')
TOL = 1e-9


def _work(fn):
    with open(fn, 'rb') as f:
        r = v6.analyze_bytes(f.read(), os.path.basename(fn))
    d, tm = v6._date_from_name(fn)
    r.setdefault('date', d)
    r.setdefault('time_start', r.get('time_start') or tm)
    return r


def rebuild(workers=2):
    files = sorted(glob.glob(os.path.join(RAW, '2026*.csv')))
    if workers > 1:
        from multiprocessing import Pool
        with Pool(workers) as p:
            rows = p.map(_work, files, chunksize=4)
    else:
        rows = [_work(f) for f in files]
    dm = pd.DataFrame(rows).sort_values(['date', 'time_start']).reset_index(drop=True)
    dm, _ = v6.postprocess_master(dm, verbose=False)
    return dm


def compare(pub, reb):
    pub = pub.set_index('file')
    reb = reb.set_index('file')
    out = dict(
        nRowsPublished=int(len(pub)), nRowsRebuilt=int(len(reb)),
        fileSetIdentical=bool(set(pub.index) == set(reb.index)),
        columnsPublished=int(pub.shape[1]), columnsRebuilt=int(reb.shape[1]),
        columnsOnlyInRebuilt=sorted(set(reb.columns) - set(pub.columns)),
        columnsOnlyInPublished=sorted(set(pub.columns) - set(reb.columns)),
    )
    reb = reb.loc[pub.index]
    common = [c for c in pub.columns if c in reb.columns]
    drifted, ident = {}, 0
    null_files = {}
    for c in common:
        x, y = pub[c], reb[c]
        nm = x.isna() != y.isna()
        both = x.notna() & y.notna()
        numeric = (pd.api.types.is_numeric_dtype(x) and pd.api.types.is_numeric_dtype(y)
                   and x.dtype != bool and y.dtype != bool)
        if numeric:
            d = (x[both].astype(float) - y[both].astype(float)).abs()
            nd = int((d > TOL).sum())
            mx = float(d.max()) if len(d) else 0.0
        else:
            nd = int((x[both].astype(str) != y[both].astype(str)).sum())
            mx = None
        if nd or int(nm.sum()):
            drifted[c] = dict(nRowsDiffer=nd, nNullPatternMismatch=int(nm.sum()),
                              maxAbsDiff=None if mx is None else round(mx, 6))
            if nm.any():
                null_files[c] = sorted(map(str, pub.index[nm]))
        else:
            ident += 1
    out['columnsCompared'] = len(common)
    out['columnsIdentical'] = ident
    out['columnsDrifted'] = drifted
    out['nullPatternMismatchFiles'] = sorted({f for v in null_files.values() for f in v})
    # canonical exclusion: file-identity equality on rows scored in BOTH
    can = {}
    for c in ('ens_invalid', 'ens_outlier_v2', 'ens_extreme'):
        if c in pub.columns and c in reb.columns:
            both = pub[c].notna() & reb[c].notna()
            px = set(pub.index[both & pub[c].astype(str).eq('True')])
            rx = set(reb.index[both & reb[c].astype(str).eq('True')])
            can[c] = dict(publishedN=int(pub[c].astype(str).eq('True').sum()),
                          rebuiltN=int(reb[c].astype(str).eq('True').sum()),
                          identicalFileSetOnCommonRows=bool(px == rx),
                          nOnlyPublished=len(px - rx), nOnlyRebuilt=len(rx - px))
    out['exclusionSets'] = can
    return out


def main():
    ap_pub, ap_out = sys.argv[1], sys.argv[2]
    workers = int(sys.argv[sys.argv.index('--workers') + 1]) if '--workers' in sys.argv else 2
    t0 = time.time()
    pub_bytes = open(ap_pub, 'rb').read()
    pub = pd.read_csv(ap_pub, low_memory=False)
    reb = rebuild(workers)
    blk = compare(pub, reb)
    import sklearn, scipy
    blk.update(
        _provenance=('GENERATED by master_refit_audit.py: full raw -> master rebuild with the versioned '
                     'builder (analyze_bytes + postprocess_master) compared with the published '
                     'drive_master.csv. drive_master.csv is not modified. Regenerate; do not hand-edit.'),
        generatedAt=datetime.datetime.now(datetime.timezone.utc).isoformat(),
        publishedMasterMD5=hashlib.md5(pub_bytes).hexdigest(),
        rebuildSeconds=round(time.time() - t0),
        packageVersions=dict(python=platform.python_version(), numpy=np.__version__,
                             pandas=pd.__version__, scipy=scipy.__version__,
                             sklearn=sklearn.__version__),
    )
    json.dump(blk, open(ap_out, 'w'), indent=1, ensure_ascii=False)
    print(json.dumps({k: blk[k] for k in ('nRowsRebuilt', 'columnsCompared', 'columnsIdentical',
                                           'columnsOnlyInRebuilt', 'nullPatternMismatchFiles')}, indent=1))


if __name__ == '__main__':
    main()
