// test_ambient_table.js (M314) — renders xtrail_dashboard.html in jsdom, opens the Thermal tab and exercises the "Ambient Temperature per Drive" section:
// month -> date grouping, default state, expand/collapse all, search by date / "Sep 27" / time, and that every drive appears when fully expanded.
const fs=require('fs');const {JSDOM}=require('jsdom');
if(typeof globalThis.MessageChannel==='undefined'){globalThis.MessageChannel=class{constructor(){this.port1={onmessage:null,postMessage:d=>setImmediate(()=>this.port1.onmessage&&this.port1.onmessage({data:d}))};this.port2={onmessage:null,postMessage:d=>setImmediate(()=>this.port2.onmessage&&this.port2.onmessage({data:d}))};const a=this.port1,b=this.port2;a.postMessage=d=>setImmediate(()=>b.onmessage&&b.onmessage({data:d}));b.postMessage=d=>setImmediate(()=>a.onmessage&&a.onmessage({data:d}));}};}
const html=fs.readFileSync(process.env.XT_HTML||'xtrail_dashboard.html','utf8');
const arrays=JSON.parse(fs.readFileSync('summary_arrays.json','utf8'));
const T=arrays.ambientTable;const errs=[];
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,beforeParse(w){w.MessageChannel=globalThis.MessageChannel;w.console.error=(...a)=>errs.push(a.join(' '));}});
const d=dom.window.document,sleep=ms=>new Promise(r=>setTimeout(r,ms)),click=el=>el.dispatchEvent(new dom.window.MouseEvent('click',{bubbles:true}));
let fails=0;const ok=(label,c)=>{console.log((c?'PASS ':'FAIL ')+label);if(!c)fails++;};
(async()=>{
  await sleep(800);
  click([...d.querySelectorAll('button')].find(b=>b.textContent.trim().toLowerCase()==='thermal'));await sleep(400);
  const root=d.querySelector('[data-amb-table]');
  ok('section present at the end of the Thermal tab', !!root);
  if(!root){process.exit(1);}
  const heads=[...d.querySelectorAll('h2')].map(h=>h.textContent.trim());
  ok('Ambient section is the LAST section of the Thermal tab', heads[heads.length-1]==='Ambient Temperature per Drive — Start / Interim / End');
  const months=[...new Set(T.rows.map(r=>r.d.slice(0,7)))], days=[...new Set(T.rows.map(r=>r.d))];
  ok(`one collapsible per month (${months.length})`, root.querySelectorAll('[data-amb-month]').length===months.length);
  const last=months[months.length-1];
  ok('latest month open, earlier months collapsed by default', [...root.querySelectorAll('[data-amb-month]')].every(m=>(m.querySelector('button').getAttribute('aria-expanded')==='true')===(m.getAttribute('data-amb-month')===last)));
  const lastDays=days.filter(x=>x.startsWith(last));
  ok(`latest month lists its ${lastDays.length} days, all collapsed (no data rows yet)`, root.querySelectorAll(`[data-amb-month="${last}"] [data-amb-date]`).length===lastDays.length && root.querySelectorAll('tbody tr').length===0);
  const btn=t=>[...root.querySelectorAll('button')].find(b=>b.textContent.trim()===t);
  click(btn('Expand all'));await sleep(200);
  ok(`Expand all shows every drive (${T.rows.length} rows)`, root.querySelectorAll('tbody tr').length===T.rows.length);
  const r0=T.rows.find(r=>r.a.length>2);
  const tr=[...root.querySelectorAll('tbody tr')].find(x=>x.textContent.includes(r0.t)&&x.closest('[data-amb-date]').getAttribute('data-amb-date')===r0.d);
  ok('a drive with interim readings shows start, every interim value and end', !!tr && r0.a.slice(1,-1).every(v=>tr.textContent.includes(String(v))) && tr.textContent.includes(String(r0.a[0])) && tr.textContent.includes(String(r0.a[r0.a.length-1])));
  click(btn('Collapse all'));await sleep(200);
  ok('Collapse all hides every data row', root.querySelectorAll('tbody tr').length===0);
  const inp=root.querySelector('input[type=search]');
  const type=v=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(inp,v);inp.dispatchEvent(new dom.window.Event('input',{bubbles:true}));};
  const sample=days[days.length-2], [yy,mm,dd]=sample.split('-'), n=T.rows.filter(r=>r.d===sample).length;
  type(sample);await sleep(200);
  ok(`search "${sample}" opens that day with its ${n} drives`, root.querySelectorAll('[data-amb-date]').length===1 && root.querySelectorAll('tbody tr').length===n);
  const mon=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][+mm-1];
  type(`${mon} ${+dd}`);await sleep(200);
  ok(`search "${mon} ${+dd}" finds the same day`, root.querySelectorAll(`[data-amb-date="${sample}"]`).length===1 && root.querySelectorAll('tbody tr').length>=n);
  type('zzzz-no-match');await sleep(200);
  ok('no-match search shows an explicit empty message', root.textContent.includes('no drive matches this search') && root.querySelectorAll('[data-amb-date]').length===0);
  type('');await sleep(200);
  ok('clearing the search restores the collapsed view', root.querySelectorAll('tbody tr').length===0 && root.querySelectorAll('[data-amb-month]').length===months.length);
  // ── M315: thermal-class chips, temperature-range filter, CSV export ──
  const chipBtn=c=>root.querySelector(`[data-amb-coh="${c}"]`);
  const setNum=(el,v)=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(el,v);el.dispatchEvent(new dom.window.Event('input',{bubbles:true}));};
  ok('class chips show the payload counts (All, Warm, Shoulder, Cold)', ['all','warm','shoulder','cold'].every(c=>!!chipBtn(c)) && ['warm','shoulder','cold'].every(c=>chipBtn(c).textContent.includes(String(T.cohortCounts[c]))));
  const coldRows=T.rows.filter(r=>r.c==='cold');
  click(chipBtn('cold'));await sleep(200);
  ok(`Cold chip lists exactly its ${coldRows.length} drives, each labelled Cold`, root.querySelectorAll('tbody tr').length===coldRows.length && [...root.querySelectorAll('tbody tr')].every(tr=>tr.textContent.includes('Cold')));
  click(chipBtn('all'));await sleep(200);
  ok('All chip clears the class filter and restores the default collapsed view', root.querySelectorAll('tbody tr').length===0);
  setNum(root.querySelector('[data-amb-lo]'),'30');await sleep(150);
  const hot=T.rows.filter(r=>r.a.some(v=>v>=30));
  ok(`"any reading >= 30 °C" lists ${hot.length} drives`, root.querySelectorAll('tbody tr').length===hot.length);
  setNum(root.querySelector('[data-amb-hi]'),'31');await sleep(150);
  const band=T.rows.filter(r=>r.a.some(v=>v>=30&&v<=31));
  ok(`"any reading 30–31 °C" lists ${band.length} drives`, root.querySelectorAll('tbody tr').length===band.length);
  let blob=null;dom.window.URL.createObjectURL=b=>{blob=b;return 'blob:test';};dom.window.URL.revokeObjectURL=()=>{};
  click(root.querySelector('[data-amb-csv]'));await sleep(150);
  const csv=blob?await new Promise(res=>{const fr=new dom.window.FileReader();fr.onload=()=>res(fr.result);fr.readAsText(blob);}):'';
  const lines=csv.trim().split('\n');
  ok(`CSV export has a header and one line per visible drive (${band.length})`, lines.length===band.length+1 && lines[0]==='date,time,drive_no,km,start_c,interim_c,end_c,mean_c,cohort,pack_start_c,oil_start_c,coolant_start_c,oil_30s_c,oil_60s_c,oil_120s_c,oil_300s_c,oil_600s_c,coolant_30s_c,coolant_60s_c,coolant_120s_c,coolant_300s_c,coolant_600s_c,cold_soak_status,file');
  const bi=band.find(r=>r.a.length>2)||band[0], bl=lines.find(l=>l.endsWith(','+bi.f));
  const bf=bl?bl.split(','):[];
  ok('CSV row carries pack/oil/coolant start temperatures, the warm-up series and the cold-soak status (M316)', !!bl && bf[9]===String(bi.p??'') && bf[10]===String(bi.o??'') && bf[11]===String(bi.w??'') && bf[15]===String(bi.ow[3]??'') && bf[20]===String(bi.cw[3]??'') && bf[22]===bi.cs);
  ok('CSV row carries start, interim (";"-joined), end, mean, class and file id', !!bl && bl.split(',')[4]===String(bi.a[0]) && bl.split(',')[5]===bi.a.slice(1,-1).join(';') && bl.split(',')[6]===String(bi.a[bi.a.length-1]) && bl.split(',')[8]===bi.c);
  setNum(root.querySelector('[data-amb-lo]'),'');setNum(root.querySelector('[data-amb-hi]'),'');await sleep(150);
  ok('clearing the range restores the default collapsed view', root.querySelectorAll('tbody tr').length===0);
  // ── M316: start temperatures, warm-up and cold-soak columns (toggle) ──
  const f1=v=>Number.isInteger(v)?String(v):v.toFixed(1);
  ok('start-temperature columns are hidden by default', !root.textContent.includes('Pack start'));
  click(btn('Expand all'));await sleep(200);
  click(root.querySelector('[data-amb-start]'));await sleep(250);
  const hd=root.querySelector('thead').textContent;
  ok('toggle adds the pack, oil, coolant, +5 min and cold-soak columns', ['Pack start','Oil start','Coolant start','Oil +5 min','Coolant +5 min','Cold soak'].every(h=>hd.includes(h)));
  const rowOf=r=>[...root.querySelectorAll('tbody tr')].find(x=>x.closest('[data-amb-date]').getAttribute('data-amb-date')===r.d && x.querySelectorAll('td')[0].textContent==='D'+r.n);
  const full=T.rows.find(r=>r.p!=null&&r.o!=null&&r.w!=null&&r.ow[3]!=null&&r.cw[3]!=null&&r.cs==='probable')||T.rows.find(r=>r.p!=null&&r.o!=null&&r.w!=null&&r.ow[3]!=null&&r.cw[3]!=null);
  const c=[...rowOf(full).querySelectorAll('td')].map(x=>x.textContent);
  ok('a drive row shows its exact pack / oil / coolant start and +5 min values', c[9]===f1(full.p)&&c[10]===f1(full.o)&&c[11]===f1(full.w)&&c[12]===f1(full.ow[3])&&c[13]===f1(full.cw[3]));
  ok('the cold-soak status is labelled', c[14]===({not_cold_soaked:'not cold-soaked',probable:'probable',cold_soaked:'cold-soaked',unknown:'unknown'}[full.cs]));
  const miss=T.rows.find(r=>r.p==null||r.o==null||r.w==null);
  if(miss){const cm=[...rowOf(miss).querySelectorAll('td')].map(x=>x.textContent);ok('a drive with a missing start temperature shows an em dash, not 0 or NaN', (miss.p==null?cm[9]==='—':true)&&(miss.o==null?cm[10]==='—':true)&&(miss.w==null?cm[11]==='—':true)&&!cm.some(x=>x==='NaN'));}
  ok('warm-up series is available on hover (title attribute)', (rowOf(full).querySelectorAll('td')[12].getAttribute('title')||'').includes('300 s'));
  click(root.querySelector('[data-amb-start]'));await sleep(200);
  ok('toggling off hides the extra columns again', !root.querySelector('thead').textContent.includes('Pack start'));
  click(btn('Collapse all'));await sleep(150);
  ok('no console errors while interacting', errs.length===0);
  if(errs.length)console.log(errs.slice(0,3).join('\n'));
  console.log(fails?`FAILED ${fails}`:'AMBIENT TABLE TEST PASSED');process.exit(fails?1:0);
})();
