"""M383 (audit F23): throughput MC with summed-curve interpolation and chunked quantization draws reproduces the former per-drive x per-draw
implementation (frozen reference copy tests/synthetic/reference/energy_uncertainty_mc_pre_m383.py) on a seeded synthetic
precompute: same random stream, every numeric leaf equal to float rounding (relative 1e-9), identical structure; peak memory is lower."""
import importlib.util, json, os, sys, tracemalloc
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
os.chdir(ROOT); sys.path.insert(0, ROOT); sys.path.insert(0, os.path.join(ROOT, "tools"))
import numpy as np
import energy_uncertainty_mc as NEW
from perf_baseline import synthetic_precompute

p = os.path.join(ROOT, "tests", "synthetic", "reference", "energy_uncertainty_mc_pre_m383.py")      # frozen copy of main after M382 (CI checks out depth 1: no git needed)
spec = importlib.util.spec_from_file_location("energy_uncertainty_mc_old", p)
OLD = importlib.util.module_from_spec(spec); spec.loader.exec_module(OLD)

pre = synthetic_precompute()
kw = dict(offset_point_a=-0.38, ci95a=(-0.42, -0.35), net_correction_kwh=21.0)


def run(mod):
    tracemalloc.start()
    out = mod.build(pre, rng=np.random.default_rng(mod.SEED), **kw)
    peak = tracemalloc.get_traced_memory()[1]
    tracemalloc.stop()
    return out, peak


def cmp(a, b, path=""):
    if isinstance(a, dict):
        assert isinstance(b, dict) and a.keys() == b.keys(), path
        return sum(cmp(a[k], b[k], f"{path}/{k}") for k in a)
    if isinstance(a, list):
        assert isinstance(b, list) and len(a) == len(b), path
        return sum(cmp(x, y, f"{path}[{i}]") for i, (x, y) in enumerate(zip(a, b)))
    if isinstance(a, float) or isinstance(b, float):
        assert abs(a - b) <= 1e-9 * max(1.0, abs(a), abs(b)), (path, a, b)
        return 1
    assert a == b or path.endswith("finding"), (path, a, b)   # the data-quality sentence is generated by the new module only when contributors exist
    return 1


old, pk_old = run(OLD)
new, pk_new = run(NEW)
n = cmp(json.loads(json.dumps(old, default=float)), json.loads(json.dumps(new, default=float)))
assert pk_new < 0.5 * pk_old, (pk_old, pk_new)
print("OK test_mc_summed_curves: %d leaves equal, peak %.0f MB -> %.0f MB" % (n, pk_old / 1e6, pk_new / 1e6))
