#!/usr/bin/env python3
"""Build summary_arrays.json -> ambientTable (M314): the per-drive ambient temperatures behind the Thermal tab section "Ambient Temperature per Drive".
Single source = summary_config.json `ambientByDrive` (driver-recorded vehicle readouts; canonical form [start, *interim, end]); drive identity, date,
start time and distance come from drive_master.csv. Nothing is typed here. Legacy entries (a bare number or a one-element list, see
tools/ambient_protocol.py) are shown as start = end and flagged `s: 1` (single recorded value).
Row keys (compact): f file id, d date YYYY-MM-DD, t start time HH:MM, n drive number within the day, k distance km, a [start, *interim, end], s 1 if single value,
c thermal class of the drive (seasonal master thermal_regime_raw: warm / shoulder / cold), m time-weighted mean ambient (seasonal master ambient_time_mean_c).
Also stamps the block (clone of the cohortMeta stamp at the current corpus hash). Idempotent; run after ingest_core (needs the new drives in the master).
Usage: python tools/build_ambient_table.py"""
import copy, datetime, hashlib, json, os
import pandas as pd

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
os.chdir(ROOT)
cfg = json.load(open("summary_config.json", encoding="utf-8"))
amb = cfg["ambientByDrive"]
dm = pd.read_csv("drive_master.csv", low_memory=False)
dm = dm.sort_values(["date", "time_start"], kind="stable").reset_index(drop=True)
sdm = pd.read_csv("seasonal_drive_master.csv", low_memory=False).set_index("file")      # thermal cohort + time-weighted mean ambient per drive
assert set(dm["file"]) <= set(sdm.index), "seasonal master does not cover every drive (run compute_seasonal first)"
missing = [f for f in dm["file"] if f not in amb]
assert not missing, f"drives without an ambientByDrive entry: {missing[:5]} (+{len(missing) - 5 if len(missing) > 5 else 0})"
rows, nlegacy = [], 0
day_n = {}
for _, r in dm.iterrows():
    v = amb[r["file"]]
    single = not (isinstance(v, list) and len(v) >= 2)
    vals = [float(x) for x in (v if isinstance(v, list) else [v])]
    if single:
        nlegacy += 1
        vals = [vals[0], vals[0]]
    day_n[r["date"]] = day_n.get(r["date"], 0) + 1
    row = {"f": r["file"], "d": str(r["date"]), "t": str(r["time_start"])[:5], "n": day_n[r["date"]],
           "k": None if pd.isna(r["distance_km"]) else round(float(r["distance_km"]), 1), "a": [int(x) if float(x).is_integer() else x for x in vals],
           "c": str(sdm.loc[r["file"], "thermal_regime_raw"]), "m": None if pd.isna(sdm.loc[r["file"], "ambient_time_mean_c"]) else round(float(sdm.loc[r["file"], "ambient_time_mean_c"]), 2)}
    if single:
        row["s"] = 1
    rows.append(row)
flat = [x for r in rows for x in r["a"]]
block = {"_provenance": ("GENERATED by tools/build_ambient_table.py from summary_config.json ambientByDrive (driver-recorded vehicle readouts, source vehicle_sensor, "
                         "uncertainty class vehicle_uncalibrated; the vehicle's ambient PID is too sparse to use) and drive_master.csv. Regenerate; do not hand-edit."),
         "format": "a = [start, ...interim, end] in chronological order; s = 1: single recorded value (legacy entry), shown as start = end; c = thermal class (raw); m = time-weighted mean ambient",
         "cohortMinDrives": int(json.load(open("seasonal_config.json", encoding="utf-8"))["cohorts"].get("minDrivesForStatistics", 10)),
         "cohortCounts": {c: int((dm["file"].map(sdm["thermal_regime_raw"]) == c).sum()) for c in ("warm", "shoulder", "cold")},
         "nDrives": len(rows), "nDays": len({r["d"] for r in rows}), "nInterimDrives": sum(1 for r in rows if len(r["a"]) > 2),
         "nSingleValueLegacy": nlegacy, "rangeC": [min(flat), max(flat)], "rows": rows}
live = hashlib.md5(open("drive_master.csv", "rb").read()).hexdigest()
A = json.load(open("summary_arrays.json", encoding="utf-8"))
A["ambientTable"] = block
s = copy.deepcopy(A["_artifactStamps"]["cohortMeta"])
s.update(corpusHash=live, generatedAt=datetime.datetime.now(datetime.timezone.utc).isoformat(), computationStatus="computed",
         computationStatusNote="M314: per-drive ambient table (tools/build_ambient_table.py) from summary_config.json ambientByDrive and drive_master.csv.")
for k in ("carriedForward", "basisNDrives", "reissuedFrom", "reissueNote"):
    s.pop(k, None)
A["_artifactStamps"]["ambientTable"] = s
with open("summary_arrays.json", "w", encoding="utf-8") as f:
    f.write(json.dumps(A, ensure_ascii=False, indent=1))
print(json.dumps({k: block[k] for k in ("nDrives", "nDays", "nInterimDrives", "nSingleValueLegacy", "rangeC")}))
