#!/usr/bin/env python3
"""Inject summary_arrays.json -> masterRefitProvenance (M311) from script outputs:
  analyses/M310_refit_audit_489_todays_raw.json   (master_refit_audit.py on the repo raw archive, 489 drives)
  analyses/M311_refit_provenance_diag.json        (tools/refit_provenance_diag.py: per-group drift, raw-derived columns)
Purpose (Director 2026-09-30): keep masterRefitAudit (original-era raw, 446 drives) as the reference of record and publish the rebuild from
the raw archive that is in git NEXT TO it, labelled provenance sensitivity. Every number is read from those files, none is typed here.
Also stamps the block (clone of the masterRefitAudit stamp, current corpus hash). Idempotent. Run after restamping, before build_html.js."""
import copy, datetime, hashlib, json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import refit_provenance_text as RT

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
P = lambda *a: os.path.join(ROOT, *a)
J = lambda *a: json.load(open(P(*a), encoding="utf-8"))

aud = J("analyses", "M310_refit_audit_489_todays_raw.json")
dia = J("analyses", "M311_refit_provenance_diag.json")
live = hashlib.md5(open(P("drive_master.csv"), "rb").read()).hexdigest()
assert aud["publishedMasterMD5"] == live, "refit audit was run on a different master than the live one; rerun master_refit_audit.py"
pg = dia["perGroup"]
block = {
    "_provenance": ("GENERATED by tools/build_refit_provenance.py from analyses/M310_refit_audit_489_todays_raw.json (master_refit_audit.py on the raw "
                    "archive held in this repository at that time: the former re-exports, before M366) and analyses/M311_refit_provenance_diag.json (tools/refit_provenance_diag.py). "
                    "PROVENANCE SENSITIVITY: the reference of record remains masterRefitAudit (original-era raw). Regenerate; do not hand-edit."),
    "label": "provenance sensitivity",
    "referenceOfRecord": "masterRefitAudit",
    "rebuildFromRepositoryArchive": {
        "nRowsRebuilt": aud["nRowsRebuilt"], "columnsCompared": aud["columnsCompared"],
        "columnsIdentical": aud["columnsIdentical"], "columnsDrifted": len(aud["columnsDrifted"]),
        "publishedMasterMD5": aud["publishedMasterMD5"], "python": dia["python"]},
    "driftByRawFileStatus": {
        "rawDerivedColumnsCompared": dia["columns_compared"],
        "newDrives": {"n": pg["new"]["n_rows"], "columnsDrifted": pg["new"]["columnsDrifted"]},
        "hashVerified": {"n": pg["hash_ok"]["n_rows"], "columnsDrifted": pg["hash_ok"]["columnsDrifted"],
                         "columns": sorted(pg["hash_ok"]["drift"]),
                         "note": "distance_km on one drive is the documented M286 distance repair (published-only provenance columns); net_draw_per100km follows from it"},
        "hashFailing": {"n": pg["hash_fail"]["n_rows"], "columnsDrifted": pg["hash_fail"]["columnsDrifted"]}},
    "basisStatus": RT.BASIS_STATUS,
    "interpretation": RT.INTERPRETATION,
    "limits": [RT.LIMIT_0,
               "Decimal-precision check on the first 30 rows of a few files did not discriminate rounding from altered content",
               "Audits ran on different Python versions (446 reference: 3.11.15; this rebuild: " + dia["python"] + "); the zero drift on new drives shows the version is not the cause"],
}
A = json.load(open(P("summary_arrays.json"), encoding="utf-8"))
A["masterRefitProvenance"] = block
st = A["_artifactStamps"]
s = copy.deepcopy(st["masterRefitAudit"])
s.update(corpusHash=live, generatedAt=datetime.datetime.now(datetime.timezone.utc).isoformat(), computationStatus="computed",
         computationStatusNote="M311: provenance-sensitivity rebuild from the repository raw archive (tools/build_refit_provenance.py); reference of record remains masterRefitAudit.")
s.pop("carriedForward", None)
s.pop("basisNDrives", None)
st["masterRefitProvenance"] = s
with open(P("summary_arrays.json"), "w", encoding="utf-8") as f:
    f.write(json.dumps(A, ensure_ascii=False, indent=1))
print(json.dumps({"injected": "masterRefitProvenance", "rebuild": block["rebuildFromRepositoryArchive"], "groups": block["driftByRawFileStatus"]}, indent=1))
