#!/usr/bin/env python3
"""F03 provenance-sensitivity artifact -> f03_provenance.json (repo root). Every number is read from a script output:
raw_manifest.json + raw/ (hash status), analyses/F03/headline_delta_scenarioA.json, analyses/F03/f1_f2_f4_results.json, analyses/F03/f3_results.json.
Usage: python tools/f03_provenance_build.py   (XT_RAW_DIR = raw dir). Wording = Director decision 2026-09-29/30 (analyses/F03/README.md)."""
import hashlib, json, os, re
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
J = lambda *p: json.load(open(os.path.join(ROOT, *p), encoding="utf-8"))
md5 = lambda *p: hashlib.md5(open(os.path.join(ROOT, *p), "rb").read()).hexdigest()

raw = os.environ.get("XT_RAW_DIR") or os.path.join(ROOT, "raw")
man = J("raw_manifest.json")
idx = {re.sub(r"\D", "", f.rsplit(".", 1)[0]): f for f in os.listdir(raw) if f.lower().endswith(".csv")}
fail_all = ok_all = fail_can = n_can = 0
for r in man["files"]:
    if not r["raw_name"] or r["role"] == "derived":      # derived aggregates (e4orce_master/ambient) are not raw captures
        continue
    k = re.sub(r"\D", "", r["raw_name"].rsplit(".", 1)[0])
    p = os.path.join(raw, idx[k]) if k in idx else os.path.join(ROOT, r["raw_name"])
    good = hashlib.sha256(open(p, "rb").read()).hexdigest() == r["sha256"]
    ok_all += good; fail_all += (not good)
    if r["role"] == "canonical":
        n_can += 1; fail_can += (not good)

hd = J("analyses", "F03", "headline_delta_scenarioA.json")
K = {k["name"]: k for k in hd["kpis"]}
f12 = J("analyses", "F03", "f1_f2_f4_results.json")
f3 = J("analyses", "F03", "f3_results.json")
sel = lambda n: {"published": K[n]["published"], "sensitivity": K[n]["fresh"], "status": K[n]["status"]}

out = {
    "_provenance": "GENERATED by tools/f03_provenance_build.py from raw_manifest.json + raw/ hashes and analyses/F03 result JSONs (M306/M307). Do not hand-edit.",
    "raw": {"nFiles": ok_all + fail_all, "nHashFailing": fail_all, "nHashMatching": ok_all, "nCanonical": n_can, "nCanonicalHashFailing": fail_can,
            "rowCountsMatchManifest": True, "originalsAvailable": False},
    "referenceOfRecord": "published master/arrays (drive_master.csv MD5 in meta/rawManifest); the rebuild is a provenance-sensitivity analysis, not a correction",
    "disclosure": (f"Published values derived from the M299 corpus; {fail_all}/{ok_all + fail_all} archived raw copies do not match recorded hashes and do not "
                   "reproduce per-drive values; originals unavailable."),
    "sensitivityStatement": ("In a provenance-sensitivity rebuild from today's raw files the cell-spread slope was not robust (sign and magnitude changed); "
                             "the difference is confined to hash-failing early-month files and is confounded with calendar month. It is a sensitivity result, not a finding."),
    "wording": ["no detectable cell-spread trend over the observation window; equivalence not established (not 'no degradation')",
                "provenance sensitivity, never 'correction' or 'error'",
                "never 'reproducible from raw data' for raw-pass keys; the published estimate is not verified against originals"],
    "metrics": [
        {"key": "degradationTrends.cellSpread.clusterRobustOLS.slope (mV/month)", "robust": False,
         **sel("degradation.cellSpread.clusterRobustOLS.slope (mV/mo)"),
         "publishedCI95": K["degradation.cellSpread.clusterRobustOLS.slope (mV/mo)"].get("publishedCI"),
         "pTOST": sel("degradation.cellSpread.pTOST")},
        {"key": "cellHealthTrend.olsSlopeMvPerMo (non-authoritative)", "robust": False, **sel("cellHealthTrend.olsSlopeMvPerMo")},
        {"key": "degradationTrends.resistanceVreg.clusterRobustOLS.slope (mOhm/month)", "robust": True, **sel("degradation.resistanceVreg.clusterRobustOLS.slope (mOhm/mo)")},
        {"key": "powerFade.slopeMohmPerMoTctrl", "robust": True, **sel("powerFade.slopeMohmPerMoTctrl")},
    ],
    "headlineKpis": {"nCompared": hd["nKpis"], "nOutsidePublishedCI": len(hd["escalate"]), "escalated": hd["escalate"],
                     "decisionFlipsCount": sum(1 for k in hd["kpis"] if k["status"] == "flip")},
    "followUps": {
        "F1_coincidentSubset": {"nDrives": f12["F1"]["nDrivesSubset"], "slope": f12["F1"]["fit"]["olsSlope"], "ci95": f12["F1"]["fit"]["olsCI95"],
                                "containsPublishedSlope": f12["F1"]["outcomes"]["containsPublishedSlope"], "reading": "not contradicted (descriptive; selected on the outcome difference)"},
        "F1b_outcomeBlindSubset": {"nDrives": f12["F1b"]["nDrivesSubset"], "slope": f12["F1b"]["fit"]["olsSlope"], "ci95": f12["F1b"]["fit"]["olsCI95"],
                                   "reading": "uninformative (Aug-Sep only, interval contains both published and rebuild slope)"},
        "F2": {"P_nFitsCIContainPublished": f"{f12['datasets']['P']['nFitsCIContainPublished']}/{f12['datasets']['P']['nFits']}",
               "rebuild_nFitsCIContainPublished": f"{f12['datasets']['A_Pexcl']['nFitsCIContainPublished']}/{f12['datasets']['A_Pexcl']['nFits']}"},
        "F3": {"explainedByPrelistedFeature": f3["explains"], "bestAUC": round(f3["bestAUC"], 3), "permutationP": f3["permutationNullMaxAUC"]["p"],
               "reading": "mechanism unexplained by the 12 pre-listed raw-file features (candidate mechanisms remain hypotheses; originals unavailable)"},
    },
    "sources": {p: md5(*p.split("/")) for p in ("raw_manifest.json", "analyses/F03/headline_delta_scenarioA.json",
                                                "analyses/F03/f1_f2_f4_results.json", "analyses/F03/f3_results.json")},
}
json.dump(out, open(os.path.join(ROOT, "f03_provenance.json"), "w", encoding="utf-8"), indent=1, ensure_ascii=False)
print(json.dumps({"raw": out["raw"], "headlineKpis": out["headlineKpis"]}, indent=1))
