#!/usr/bin/env python3
"""F03 provenance-sensitivity artifact -> f03_provenance.json (repo root). Every number is read from a script output:
raw_manifest.json + raw/ (hash status), analyses/F03/headline_delta_scenarioA.json, analyses/F03/f1_f2_f4_results.json, analyses/F03/f3_results.json.
Usage: python tools/f03_provenance_build.py   (XT_RAW_DIR = raw dir). Wording = Director decision 2026-09-29/30 (analyses/F03/README.md)."""
import hashlib, json, os, re
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
J = lambda *p: json.load(open(os.path.join(ROOT, *p), encoding="utf-8"))
md5 = lambda *p: hashlib.md5(open(os.path.join(ROOT, *p), "rb").read()).hexdigest()

raw = os.environ.get("XT_RAW_DIR") or os.path.join(ROOT, "raw")
man = J("raw_manifest.json")
idx = {re.sub(r"\D", "", f.rsplit(".", 1)[0]): f for f in os.listdir(raw) if f.lower().endswith(".csv")}
fail_all = ok_all = fail_can = n_can = 0
for r in man["files"]:
    if not r["raw_name"] or r["role"] == "derived":      # derived aggregates (e4orce_master/ambient) are not raw captures
        continue
    k = re.sub(r"\D", "", r["raw_name"].rsplit(".", 1)[0])
    p = os.path.join(raw, idx[k]) if k in idx else os.path.join(ROOT, r["raw_name"])
    good = hashlib.sha256(open(p, "rb").read()).hexdigest() == r["sha256"]
    ok_all += good; fail_all += (not good)
    if r["role"] == "canonical":
        n_can += 1; fail_can += (not good)

om = J("originals_manifest.json")        # M325: inventory of the external sha256-verified originals (not an archive of record)
GATE = J("analyses", "F03_originals", "M366_headline_gate.json")
ARCH = J("analyses", "F03_originals", "archived_reexports_sha256.json")          # M366: the 333 lower-precision re-exports archived before raw/ was overwritten by the originals
assert om["allVerifiedAgainstManifest"] and om["nRecords"] == ARCH["n"], "originals_manifest.json does not cover every archived re-export"
assert fail_can == 0, f"raw/ must hold the sha256-verified originals after M366 ({fail_can} canonical files still fail the manifest hash)"
hd = J("analyses", "F03", "headline_delta_scenarioA.json")
K = {k["name"]: k for k in hd["kpis"]}
f12 = J("analyses", "F03", "f1_f2_f4_results.json")
f3 = J("analyses", "F03", "f3_results.json")
WINDOW = J("summary_arrays.json")["degradationTrends"]["cellSpread"]["windowMonths"]
st = [k["status"] for k in hd["kpis"]]
others = [k for k in hd["kpis"] if k["status"] == "changed_no_ci"]
sel = lambda n: {"published": K[n]["published"], "sensitivity": K[n]["fresh"], "status": K[n]["status"]}

out = {
    "_provenance": "GENERATED by tools/f03_provenance_build.py from raw_manifest.json + raw/ hashes and analyses/F03 result JSONs (M306/M307). Do not hand-edit.",
    "raw": {"nFiles": ok_all + fail_all, "nHashFailing": fail_all, "nHashMatching": ok_all, "nCanonical": n_can, "nCanonicalHashFailing": fail_can,
            "rowCountsMatchManifest": True, "originalsAvailable": True,
            "formerReexportsReplaced": ARCH["n"], "reexportArchive": "raw_reexports_archived_2026-10-04 (outside the repo); sha256 list analyses/F03_originals/archived_reexports_sha256.json"},
    "originals": {"nRecovered": om["nRecords"], "allSha256VerifiedAgainstManifest": om["allVerifiedAgainstManifest"], "archiveOfRecord": om["archiveOfRecord"],
                  "status": om["status"], "location": om["location"], "verifiedAt": om["verifiedAt"],
                  "registeredAs": om.get("registeredAs"), "ownerDecision": om.get("ownerDecision"), "backup": om.get("backup")},
    "referenceOfRecord": "published master/arrays (drive_master.csv MD5 in meta/rawManifest); the rebuild is a provenance-sensitivity analysis, not a correction",
    "disclosure": (f"raw/ holds the sha256-verified originals: the {ARCH['n']} lower-precision re-exports among the {n_can} canonical files were replaced by them (M366, owner decision 2026-10-04), "
                   f"so {n_can - fail_can}/{n_can} canonical files match raw_manifest.json; the removed re-exports are archived outside the repo with their sha256 list. "
                   f"{GATE['ciSummary']['nChecked'] - GATE['ciSummary']['nOutsideBaselineCi']} of {GATE['ciSummary']['nChecked']} CI-checkable estimates remain inside their previous 95% CIs after the replacement; the {GATE['ciSummary']['nOutsideBaselineCi']} outside are all FUEL-12 (Fuel tab; M366 headline gate); drive_master.csv is unchanged. ML/refit columns still drift on a clean-room refit (open item), "
                   "the clean-room raw-to-master rebuild therefore remains open; the originals' inventory is originals_manifest.json (a second sha256-manifested archive, not the archive of record)."),
    "sensitivityStatement": ("Before M366, a provenance-sensitivity rebuild from the lower-precision re-exports changed the cell-spread slope (sign and magnitude); the difference arose only in the files that were re-exports "
                             "and could not be separated from calendar month. raw/ now holds the sha256-verified originals; the no-new-drive control build (M366) shows no change in degradationTrends. "
                             "The earlier rebuild result is kept as history in analyses/F03, not as a finding."),
    "wording": [f"cell-spread trend not resolved over the {WINDOW}-month window; equivalence not established (not 'no degradation')",
                "provenance sensitivity, never 'correction' or 'error'",
                "never 'reproducible from raw data' for raw-pass keys; say 'a rebuild from the sha256-verified originals is consistent with the published raw-derived non-ML per-drive values' (never 'proven', 'authenticated', 'corrections')"],
    "metrics": [
        {"key": "degradationTrends.cellSpread.clusterRobustOLS.slope (mV/month)", "robust": False,
         **sel("degradation.cellSpread.clusterRobustOLS.slope (mV/mo)"),
         "publishedCI95": K["degradation.cellSpread.clusterRobustOLS.slope (mV/mo)"].get("publishedCI"),
         "pTOST": sel("degradation.cellSpread.pTOST")},
        {"key": "cellHealthTrend.olsSlopeMvPerMo (non-authoritative)", "robust": False, **sel("cellHealthTrend.olsSlopeMvPerMo")},
        {"key": "degradationTrends.resistanceVreg.clusterRobustOLS.slope (mOhm/month)", "robust": True, **sel("degradation.resistanceVreg.clusterRobustOLS.slope (mOhm/mo)")},
        {"key": "powerFade.slopeMohmPerMoTctrl", "robust": True, **sel("powerFade.slopeMohmPerMoTctrl")},
    ],
    "headlineKpis": {"nCompared": hd["nKpis"], "nOutsidePublishedCI": len(hd["escalate"]), "escalated": hd["escalate"],
                     "nInsidePublishedCI": st.count("inside_ci"), "nUnchanged": st.count("same"),
                     "nChangedNoPublishedCI": len(others), "nNotComparable": st.count("path_missing"),
                     "maxAbsRelDeltaPctNoCI": round(max(abs(k["relDeltaPct"]) for k in others if k.get("relDeltaPct") is not None and "pTOST" not in k["name"]), 3),   # p-values excluded (reported separately)
                     "decisionFlipsCount": sum(1 for k in hd["kpis"] if k["status"] == "flip"),
                     "cellSpreadTostP": {"published": K["degradation.cellSpread.pTOST"]["published"], "rebuild": K["degradation.cellSpread.pTOST"]["fresh"],
                                         "equivalentPublished": K["degradation.cellSpread.equivalent [decision]"]["published"],
                                         "equivalentRebuild": K["degradation.cellSpread.equivalent [decision]"]["fresh"]}},
    "followUps": {
        "F1_coincidentSubset": {"nDrivesSelected": f12["F1"]["nDrivesSubset"], "nObs": f12["F1"]["fit"]["nObs"], "nDays": f12["F1"]["fit"]["nDays"], "slope": f12["F1"]["fit"]["olsSlope"], "ci95": f12["F1"]["fit"]["olsCI95"],
                                "containsPublishedSlope": f12["F1"]["outcomes"]["containsPublishedSlope"], "reading": "not contradicted (descriptive; selected on the outcome difference)"},
        "F1b_outcomeBlindSubset": {"nDrivesSelected": f12["F1b"]["nDrivesSubset"], "nObs": f12["F1b"]["fit"]["nObs"], "nDays": f12["F1b"]["fit"]["nDays"], "slope": f12["F1b"]["fit"]["olsSlope"], "ci95": f12["F1b"]["fit"]["olsCI95"],
                                   "reading": "uninformative (Aug-Sep only, interval contains both published and rebuild slope)"},
        "F2": {"P_nFitsCIContainPublished": f"{f12['datasets']['P']['nFitsCIContainPublished']}/{f12['datasets']['P']['nFits']}",
               "rebuild_nFitsCIContainPublished": f"{f12['datasets']['A_Pexcl']['nFitsCIContainPublished']}/{f12['datasets']['A_Pexcl']['nFits']}"},
        "F3": {"explainedByPrelistedFeature": f3["explains"], "bestAUC": round(f3["bestAUC"], 3), "permutationP": f3["permutationNullMaxAUC"]["p"],
               "reading": "mechanism unexplained by the 12 pre-listed raw-file features (AUC < 0.9 is not 'no difference'; candidate mechanisms remain hypotheses; lower-precision re-export of the then re-exported raw/ copies was identified after this test (M323) and was not among the pre-listed features; those copies were replaced by the originals (M366))"},
    },
    "sources": {p: md5(*p.split("/")) for p in ("raw_manifest.json", "analyses/F03/headline_delta_scenarioA.json",
                                                "analyses/F03/f1_f2_f4_results.json", "analyses/F03/f3_results.json", "originals_manifest.json")},
}
json.dump(out, open(os.path.join(ROOT, "f03_provenance.json"), "w", encoding="utf-8"), indent=1, ensure_ascii=False)
print(json.dumps({"raw": out["raw"], "headlineKpis": out["headlineKpis"]}, indent=1))
