#!/usr/bin/env python3
"""GTR-family refresh splice (M377b, analyses/M377_spec.md Rev 4; generic successor of m373_p2_splice.py / m375_splice.py, no hard-wired run files).
Reads analyses/M377_O_blocks.json (written by `tools/m373_point.py --point O --tag M377` on the live corpus) and updates, in ONE deep-diff-allow-listed pass:
  generatorTractionRecon.{sensitivity, simultaneity, speedSplit}   values only (row key sets and axis labels must equal the previous ones)
  generatorTractionRecon.refreshedBlocks                           nDrives / nDays / status counts / sources / gates rebuilt; the raw-swap provenance fields are CARRIED (basis M375)
  generatorTractionRecon.eligibilityAlignment                      current / nFuelInstrumentedRows / excluded / counts in note regenerated from the files; previous / changedFields / sensitivityNote frozen (basis M375)
  generatorTractionRecon.gtrClosure.scope.excludedNote             regenerated by gtr_closure_block.build(); closure NUMBERS are carried (M372 set), disclosed by
                                                                   gtrClosure.scope.carriedAtIngestion and by a gtrClosure entry in staleBlocks (like crossval); refresh = M377c
Refuses (exit 3, nothing written) on any STOP: O file not bound to this spec / master / gates; nDrives or clean-ID hash differ from the live headline set; sensitivity BASE differs from the
live headline; a row key-set or axis-label change; a reading flip; an escalation-band breach (speedSplit f_gen or simultaneity share move > the band, n_days change > 20 %);
a deep-diff outside the allow-list. A block-by-block delta (previous vs new, n drives, n days) is written to analyses/gtr_family_delta.json (also on STOP).
Usage: python tools/gtr_family_refresh_splice.py [--label M376] [--dry-run]"""
import argparse, copy, hashlib, json, os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
os.chdir(ROOT)
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "tools"))
sha = lambda p: hashlib.sha256(open(p, "rb").read()).hexdigest()
md5 = lambda p: hashlib.md5(open(p, "rb").read()).hexdigest()
BAND_FGEN = 0.05          # absolute, fractions (speedSplit fGen)
BAND_SHARE_PP = 5.0       # simultaneity shares are percentages: 0.05 of 100 % = 5 percentage points
BAND_NDAYS = 0.20
BLOCKS = ("sensitivity", "simultaneity", "speedSplit")
SHARES = ("genPlusBattDischarge", "chargesAndDrives", "genAloneNeutral", "fullyBanked")
CARRIED_KEYS = ("provenanceMaxAbsDelta_O_minus_R", "provenanceMaxAbsDeltaUnrounded_O_minus_R", "deadbandMaxAbsDeltaPP_O_minus_R", "previousBlock", "provenanceDelta")
CARRIED_BASIS = "M375 / 489 drives; M366 raw-swap provenance, not recomputed"
ALLOW = ["/generatorTractionRecon/" + b for b in BLOCKS + ("refreshedBlocks", "eligibilityAlignment", "staleBlocks")] + [
    "/generatorTractionRecon/gtrClosure/scope/excludedNote", "/generatorTractionRecon/gtrClosure/scope/carriedAtIngestion", "/seasonalCharts/charts/GeneratorTractionRecon"]


def walk(a, b, path=""):
    """Yield the paths at which a and b differ (lists of different length are reported at the list path)."""
    if isinstance(a, dict) and isinstance(b, dict):
        for k in sorted(set(a) | set(b)):
            yield from walk(a.get(k), b.get(k), f"{path}/{k}")
    elif isinstance(a, list) and isinstance(b, list) and len(a) == len(b):
        for i, (x, y) in enumerate(zip(a, b)):
            yield from walk(x, y, f"{path}[{i}]")
    elif a != b:
        yield path


def plan(A, O, label, spec_sha, master_md5):
    """Pure core (testable): returns (new_arrays, delta, stops)."""
    stops = []
    G = A["generatorTractionRecon"]
    new = copy.deepcopy(A)
    N = new["generatorTractionRecon"]
    m = O["meta"]
    # ---- binding / gates ----
    if m.get("specSha256") != spec_sha:
        stops.append("O file is not bound to the current analyses/M377_spec.md sha256")
    if m.get("driveMasterMd5After") != master_md5 or m.get("driveMasterMd5Before") != master_md5:
        stops.append("O file was produced on a different drive_master.csv")
    if not m["sensitivityBaseGate"]["passed"] or not m["speedSplitValidation"]["passed"]:
        stops.append("runner gate failed")
    corpus = G["corpus"] if "corpus" in G else None
    if m["driveIds"]["nClean"] != G["nDrives"]:
        stops.append("O nClean %s != live headline nDrives %s" % (m["driveIds"]["nClean"], G["nDrives"]))
    base = O["sensitivity"]["axes"][0]
    if (base["gen100"], base["trac100"], base["fgen"], base["etaBus"]) != tuple(G["sensitivity"][0][k] for k in ("gen100", "trac100", "fgen", "etaBus")) and \
            m["sensitivityBaseGate"]["target"] != {"gen100": base["gen100"], "trac100": base["trac100"], "fgen": base["fgen"], "etaBus": base["etaBus"]}:
        stops.append("sensitivity BASE differs from the live headline target")
    vals = {"sensitivity": [{k: r[k] for k in ("axis", "gen100", "trac100", "fgen", "etaBus")} for r in O["sensitivity"]["axes"]],
            "simultaneity": O["simultaneity"]["rows"], "speedSplit": O["speedSplit"]["bins"]}
    nn = {"sensitivity": (O["sensitivity"]["nDrives"], O["sensitivity"]["nDays"]), "simultaneity": (O["simultaneity"]["nDrives"], O["simultaneity"]["nDays"]),
          "speedSplit": (O["speedSplit"]["nDrives"], O["speedSplit"]["nDays"])}
    # ---- key sets ----
    for b in BLOCKS:
        old = G[b]
        if len(old) != len(vals[b]) or any(set(x) != set(y) for x, y in zip(old, vals[b])):
            stops.append(f"{b}: row key set / row count differs from the previous block")
    if [r["axis"] for r in G["sensitivity"]] != [r["axis"] for r in vals["sensitivity"]]:
        stops.append("sensitivity: axis labels differ")
    # ---- reading flips (frozen M373 list) ----
    if any(r["fgen"] >= 0.5 for r in vals["sensitivity"]):
        stops.append("reading flip: sensitivity f_gen >= 0.5 on an axis")
    sp = {r["bin"]: r for r in vals["speedSplit"]}
    if sp["90-120"]["fGen"] < sp["20-60"]["fGen"]:
        stops.append("reading flip: speedSplit f_gen decreases from the 20-60 bin to the 90-120 bin")
    si = {r["type"]: r for r in vals["simultaneity"]}
    if not si["urban"]["genPlusBattDischarge"] < si["highway"]["genPlusBattDischarge"] or not si["urban"]["chargesAndDrives"] > si["highway"]["chargesAndDrives"]:
        stops.append("reading flip: simultaneity urban vs highway ordering")
    # ---- escalation band (quantities without a CI) and delta ----
    delta = {"label": label, "bands": {"speedSplitFgenAbs": BAND_FGEN, "simultaneityShareAbsPP": BAND_SHARE_PP, "nDaysRelative": BAND_NDAYS}, "blocks": {}}
    old_rb = {r["block"]: r for r in G["refreshedBlocks"]}
    if any("key set" in x or "axis labels" in x for x in stops):      # moves are only defined on equal key sets
        return None, delta, stops
    for b in BLOCKS:
        d = {"nDrives": {"previous": old_rb[b]["nDrives"], "new": nn[b][0]}, "nDays": {"previous": old_rb[b]["nDays"], "new": nn[b][1]}}
        rel = abs(nn[b][1] - old_rb[b]["nDays"]) / old_rb[b]["nDays"]
        d["nDaysRelativeChange"] = round(rel, 4)
        if rel > BAND_NDAYS:
            stops.append(f"{b}: n_days changed by {rel:.0%} (> {BAND_NDAYS:.0%})")
        if b == "sensitivity":
            d["maxAbsMove"] = {k: round(max(abs(x[k] - y[k]) for x, y in zip(vals[b], G[b])), 6) for k in ("gen100", "trac100", "fgen", "etaBus")}
        elif b == "simultaneity":
            mv = {k: round(max(abs(x[k] - y[k]) for x, y in zip(vals[b], G[b])), 4) for k in SHARES}
            d["maxAbsMovePP"] = mv
            if max(mv.values()) > BAND_SHARE_PP:
                stops.append(f"simultaneity: a share moved by more than {BAND_SHARE_PP} pp")
        else:
            mv = max(abs(x["fGen"] - y["fGen"]) for x, y in zip(vals[b], G[b]))
            d["maxAbsMoveFgen"] = round(mv, 6)
            if mv > BAND_FGEN:
                stops.append(f"speedSplit: f_gen moved by more than {BAND_FGEN}")
        delta["blocks"][b] = d
    if stops:
        return None, delta, stops
    # ---- replace values ----
    for b in BLOCKS:
        N[b] = vals[b]
    n_fuel = len(__import__("pandas").read_csv("fuel_recon_master.csv"))
    rb = []
    for e in G["refreshedBlocks"]:
        b = e["block"]
        n_set = m["driveIds"]["nClean"] if b != "speedSplit" else nn[b][0]
        r = copy.deepcopy(e)
        r.update(nDrives=nn[b][0], nDays=nn[b][1], rerunMilestone=label,
                 status="descriptive point values, no interval; drive set = canonical-clean (ens_outlier_v2), %d of %d fuel-instrumented drives; recomputed on the live corpus at ingestion %s" % (n_set, n_fuel, label))
        r["source"] = {"O": "analyses/M377_O_blocks.json sha256 " + sha("analyses/M377_O_blocks.json")[:16], "spec": "analyses/M377_spec.md sha256 " + spec_sha[:16], "scripts": m["scriptSha256"]}
        if b == "sensitivity":
            r["baseGate"] = {"passed": m["sensitivityBaseGate"]["passed"], "equalsLiveHeadline": m["sensitivityBaseGate"]["base"], "nClean": m["sensitivityBaseGate"]["nClean"]}
        if b == "speedSplit":
            r["validation"] = {**m["speedSplitValidation"], "toleranceKwhPer100km": 0.01}
        if any(k in r for k in CARRIED_KEYS):
            r["carriedBasis"] = CARRIED_BASIS
        rb.append(r)
    N["refreshedBlocks"] = rb
    # ---- eligibility alignment: live counts from the files; frozen M375 record kept ----
    import pandas as pd
    import wire_gtr_seasonal as W
    merged = W.load_merged()
    exc = merged[merged["ens_excluded"]]
    excluded = [{"file": r.file, "drive_type": r.drive_type, "date": str(r.date), "km": float(r.distance_km), "fGenIsNaN": bool(pd.isna(r.f_gen)), "regime": r.thermal_regime,
                 "reason": "ens_outlier_v2 / ens_invalid flagged in drive_master.csv"} for r in exc.itertuples()]
    E = N["eligibilityAlignment"]
    cur = {k: N[k] for k in ("nProduction", "nDrives", "kmProduction")}
    old_note = E["note"]
    head, rest = old_note.split("), now ", 1)
    head += "), "
    tail = rest.split(". Excluded fuel-instrumented drives: ", 1)[1]
    clauses = tail[tail.index(". All-view") + 2:] if ". All-view" in tail else None
    assert clauses is not None, "eligibilityAlignment.note layout changed: STOP"
    exl = "; ".join(f"{e['file'].replace('.csv', '')} ({e['drive_type']}, {e['km']} km, {'f_gen NaN' if e['fGenIsNaN'] else 'f_gen present'})" for e in excluded)
    E["note"] = head + f"now {cur['nProduction']} / {cur['nDrives']} / {cur['kmProduction']} km. Excluded fuel-instrumented drives: " + exl + ". " + clauses
    E.update(current=cur, nFuelInstrumentedRows=n_fuel, excluded=excluded)
    E["basisFrozenRecord"] = "previous / changedFields / sensitivityNote: M375 record (489 drives), not recomputed; current / excluded / nFuelInstrumentedRows: live files"
    # ---- closure: set note from the files, numbers carried ----
    sys.argv = [sys.argv[0]] + [a for a in sys.argv[1:] if a != "--m372"] + ["--m372"]
    import gtr_closure_block as GB
    cb = GB.build()
    oldc = copy.deepcopy(G["gtrClosure"])
    newc = copy.deepcopy(cb)
    oldc["scope"]["excludedNote"] = newc["scope"]["excludedNote"]
    if oldc != newc:
        stops.append("gtrClosure: the regenerated block differs from the carried one beyond scope.excludedNote (closure refresh = M377c)")
    else:
        sc = N["gtrClosure"]["scope"]
        sc["excludedNote"] = cb["scope"]["excludedNote"]
        sc["carriedAtIngestion"] = {"basisNDrives": sc["nDrives"], "basisNDays": sc["nDays"], "milestone": "M372",
                                    "note": "closure numbers carried at the M372 set (%d drives); not recomputed on the live corpus; refresh = follow-up milestone M377c" % sc["nDrives"]}
        sb = N["staleBlocks"]
        if "gtrClosure" not in sb["blocks"]:
            sb["blocks"] = sorted(sb["blocks"] + ["gtrClosure"], key=lambda x: (x != "crossval", x))
            sb["perBlock"] = [p for p in sb["perBlock"]] + [{"block": "gtrClosure", "basisMilestone": "M372", "nDrives": sc["nDrives"], "nDays": sc["nDays"], "rawBasis": "raw/ = sha256-verified originals (M366)",
                                                              "status": "carried at the M372 set (%d drives); not recomputed on the live corpus; refresh pending (M377c)" % sc["nDrives"], "source": "payload generatorTractionRecon.gtrClosure"}]
            sb["perBlock"].sort(key=lambda p: sb["blocks"].index(p["block"]))
    if stops:
        return None, delta, stops
    # ---- deep diff against the allow-list ----
    bad = [p for p in walk(A, new) if not any(p == a or p.startswith(a + "/") or p.startswith(a + "[") for a in ALLOW)]
    if bad:
        stops.append("deep-diff outside the allow-list: %s" % bad[:5])
        return None, delta, stops
    delta["changedPaths"] = len(list(walk(A, new)))
    return new, delta, stops


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--label", default=os.environ.get("XT_INGEST_LABEL", "ingestion"))
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    O = json.load(open("analyses/M377_O_blocks.json", encoding="utf-8"))
    A = json.load(open("summary_arrays.json", encoding="utf-8"))
    new, delta, stops = plan(A, O, a.label, sha("analyses/M377_spec.md"), md5("drive_master.csv"))
    delta["stops"] = stops
    with open("analyses/gtr_family_delta.json", "w", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(delta, indent=1, ensure_ascii=False) + "\n")
    if stops:
        print("STOP (Director): " + "; ".join(stops), file=sys.stderr)
        sys.exit(3)
    if a.dry_run:
        print("dry run ok;", delta["changedPaths"], "changed leaves")
        return
    with open("summary_arrays.json", "w", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(new, ensure_ascii=False, indent=1))
    print("spliced", list(BLOCKS), "+ refreshedBlocks, eligibilityAlignment, closure set note;", delta["changedPaths"], "changed leaves")


if __name__ == "__main__":
    main()
