#!/usr/bin/env python3
"""M325: originals_manifest.json (repo root) - INVENTORY of the external sha256-verified originals of the canonical raw files whose raw/ copy fails
raw_manifest.json (spec analyses/M325_spec.md rev 2). Not a re-anchoring: archiveOfRecord is false, raw/ and raw_manifest.json are never touched,
nothing but tools/f03_provenance_build.py (counts/availability) reads it. Fails loudly (writes nothing) if the originals folder is missing, a file is
absent, or a sha256 differs from raw_manifest.json. Provenance of each original (source archive/member) is taken from the recovery report.
Usage: python tools/originals_manifest.py ORIGINALS_DIR RECOVERY_REPORT.json   (XT_RAW_DIR = raw dir, default raw/)"""
import datetime, hashlib, json, os, re, sys
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "originals_manifest.json")
if len(sys.argv) != 3:
    sys.exit(__doc__)
odir, rep = os.path.abspath(sys.argv[1]), sys.argv[2]
if not os.path.isdir(odir):
    sys.exit(f"originals folder not found: {odir} (nothing written)")
raw = os.environ.get("XT_RAW_DIR") or os.path.join(ROOT, "raw")
man = [r for r in json.load(open(os.path.join(ROOT, "raw_manifest.json"), encoding="utf-8"))["files"] if r["role"] == "canonical"]
dg = lambda s: re.sub(r"\D", "", str(s).rsplit(".", 1)[0])[:14]
idx = {dg(f): f for f in os.listdir(raw) if f.lower().endswith(".csv")}
src = {r["record_id"]: r for r in json.load(open(rep, encoding="utf-8"))["files"] if r.get("recovered")}
failing = []
for r in man:
    p = os.path.join(raw, idx[dg(r["record_id"])])
    if hashlib.sha256(open(p, "rb").read()).hexdigest() != r["sha256"]:
        failing.append(r)
recs = []
for r in sorted(failing, key=lambda r: r["record_id"]):
    p = os.path.join(odir, r["record_id"])
    if not os.path.isfile(p):
        sys.exit(f"missing original for {r['record_id']} (nothing written)")
    b = open(p, "rb").read()
    if hashlib.sha256(b).hexdigest() != r["sha256"]:
        sys.exit(f"sha256 mismatch for {r['record_id']} (nothing written)")
    s = src.get(r["record_id"], {})
    recs.append({"record_id": r["record_id"], "sha256": r["sha256"], "bytes": len(b), "source_archive": s.get("source"),
                 "source_member": s.get("source_name"), "n_sources": s.get("n_sources"), "verified_against_manifest": True})
doc = {"_provenance": "GENERATED by tools/originals_manifest.py; do not hand-edit.",
       "archiveOfRecord": False,
       "status": "registered as a second sha256-manifested archive (owner decision 2026-10-03, option 2); not the archive of record; re-anchoring (replacing raw/) undecided",
       "registeredAs": "second sha256-manifested archive of the canonical originals whose raw/ copy fails raw_manifest.json",
       "ownerDecision": {"date": "2026-10-03", "by": "Andrii", "option": 2, "text": "register the originals as a second sha256-manifested archive; raw/ and raw_manifest.json unchanged; replacing raw/ (option 3) only after a no-new-drive control build, decided separately"},
       "backup": "owner-held backups of all raw CSVs (stated by Andrii 2026-10-03; not verifiable from the repository)",
       "location": f"outside the repository, relative to the repo root: {os.path.relpath(odir, ROOT).replace(os.sep, '/')}",
       "expectedCount": len(failing), "nRecords": len(recs), "allVerifiedAgainstManifest": len(recs) == len(failing),
       "verifiedAt": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"), "records": recs}
tmp = OUT + ".tmp"
with open(tmp, "w", encoding="utf-8", newline="\n") as f:
    json.dump(doc, f, indent=1, ensure_ascii=False)
    f.write("\n")
os.replace(tmp, OUT)
print(json.dumps({k: v for k, v in doc.items() if k != "records"}, indent=1))
