#!/usr/bin/env python3
"""Ingestion stage (M389): re-issue the artifact stamps and refresh the MC data-quality note, the two steps that were run by hand after ingest_core
at M376..M388 (tools/restamp_blocks.py, tools/stamp_notes.py, tools/mc_dq_note_refresh.py).
Every key whose _artifactStamps.corpusHash differs from the live drive_master.csv MD5 is looked up in STAMP_POLICY (regenerated by a named stage, or
carried at a basis). A stale key with NO policy entry STOPS the stage (exit 1, nothing written): a new block needs a human decision about regenerated vs
carried. A carried key needs its previous basisNDrives (read from its existing stamp; never typed). The generatorTractionRecon note is generated from the
payload (tools/stamp_notes.gtr_stamp_note). Notes carry the milestone label from XT_INGEST_LABEL (required).
Usage: XT_INGEST_LABEL=M### python tools/restamp_ingest.py [--dry-run]    Idempotent (a second run finds nothing stale)."""
import hashlib, json, os, subprocess, sys
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

STAMP_POLICY = {
    "assumptionsRegistry": ("regen", "regenerated by apply_m284_post.sh (patch_m284_data.py) on the {n}-drive corpus"),
    "cohortMeta": ("regen", "regenerated by refresh_cohort_meta.py on the {n}-drive corpus"),
    "crossVehicle": ("regen", "recomputed by the arrays build on the {n}-drive corpus (provenance gate basis {n})"),
    "generatorTractionRecon": ("gtr", None),
    "provenanceSensitivity": ("regen", "regenerated by f03_provenance_build.py on the {n}-drive corpus"),
    "seasonalCharts": ("regen", "regenerated by compute_seasonal.py and the seasonal refresh stages on the {n}-drive corpus"),
    "masterRefitAudit": ("carried", "clean-room refit audit not re-run (master_refit_audit.py is audit-only)"),
    "masterRefitProvenance": ("carried", "F03/F02 raw-archive provenance facts, unchanged by this ingestion"),
}


def plan(stamps, live_md5, n_drives):
    """Returns [(key, kind, note, basis)] for every stale stamp; raises ValueError for a stale key without a policy or a carried key without a basis."""
    out, unknown = [], []
    for k, s in sorted(stamps.items()):
        if not isinstance(s, dict) or s.get("corpusHash") in (None, live_md5):
            continue
        if k not in STAMP_POLICY:
            unknown.append(k)
            continue
        kind, note = STAMP_POLICY[k]
        basis = None
        if kind == "carried":
            basis = s.get("basisNDrives")
            if not isinstance(basis, int):
                raise ValueError(f"carried key {k} has no previous basisNDrives in its stamp: decide the basis by hand (tools/restamp_blocks.py)")
        out.append((k, kind, None if note is None else note.format(n=n_drives), basis))
    if unknown:
        raise ValueError(f"stale stamp(s) without a policy entry: {unknown}: decide regenerated vs carried by hand (tools/restamp_blocks.py), then add them to STAMP_POLICY")
    return out


def main():
    dry = "--dry-run" in sys.argv
    label = os.environ.get("XT_INGEST_LABEL")
    if not label:
        print("XT_INGEST_LABEL (milestone id) is required"); return 2
    sys.path.insert(0, os.path.join(ROOT, "tools"))
    live = hashlib.md5(open(os.path.join(ROOT, "drive_master.csv"), "rb").read()).hexdigest()
    A = json.load(open(os.path.join(ROOT, "summary_arrays.json"), encoding="utf-8"))
    n = A.get("meta", {}).get("totalDrives")
    try:
        todo = plan(A.get("_artifactStamps") or {}, live, n)
    except ValueError as e:
        print("STOP:", e); return 1
    print(json.dumps({"label": label, "liveMd5": live, "nDrives": n, "stale": [t[0] for t in todo]}))
    if dry or not todo:
        pass
    else:
        cmd = [sys.executable, "tools/restamp_blocks.py", "--milestone", label]
        for k, kind, note, basis in todo:
            if kind == "regen":
                cmd += ["--regen", f"{k}={note}"]
            elif kind == "gtr":
                cmd += ["--regen", f"{k}=placeholder, replaced by tools/stamp_notes.py"]
            else:
                cmd += ["--carried", f"{k}={basis}={note}"]
        rc = subprocess.run(cmd, cwd=ROOT).returncode
        if rc:
            return rc
        if any(t[1] == "gtr" for t in todo):
            rc = subprocess.run([sys.executable, "tools/stamp_notes.py", "--milestone", label], cwd=ROOT).returncode
            if rc:
                return rc
    # the M382 F03 step (nominal energy of each MC data-quality contributor from the master); idempotent, allow-list guarded
    return subprocess.run([sys.executable, "tools/mc_dq_note_refresh.py"] + (["--dry-run"] if dry else []), cwd=ROOT).returncode


if __name__ == "__main__":
    sys.exit(main())
