#!/usr/bin/env python3
"""Generate docs/script_index.md: for each .py/.js/.jsx at repo root, file size/lines, module docstring first line, and
top-level def/class/function names with line numbers - so agents grep the index instead of reading 17k-line files.
Usage: python tools/script_index.py"""
import ast, glob, os, re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def py_entry(path):
    src = open(path, encoding="utf-8", errors="replace").read()
    try:
        t = ast.parse(src)
    except SyntaxError as e:
        return f"(syntax error: {e})", []
    doc = (ast.get_docstring(t) or "").strip().splitlines()
    first = doc[0][:160] if doc else ""
    defs = [(n.lineno, n.name) for n in t.body if isinstance(n, (ast.FunctionDef, ast.ClassDef))]
    return first, defs


def js_entry(path):
    src = open(path, encoding="utf-8", errors="replace").read().splitlines()
    first = next((l.strip("/* ").strip() for l in src[:5] if l.strip()), "")[:160]
    pat = re.compile(r"^(?:async\s+)?function\s+([A-Za-z0-9_$]+)|^const\s+([A-Z][A-Za-z0-9_]+)\s*=")
    defs = []
    for i, l in enumerate(src):
        m = pat.match(l)
        if m:
            defs.append((i + 1, m.group(1) or m.group(2)))
    return first, defs


def main():
    out = ["# Script index (generated by tools/script_index.py)", ""]
    for p in sorted(glob.glob(os.path.join(ROOT, "*.py")) + glob.glob(os.path.join(ROOT, "*.js")) + glob.glob(os.path.join(ROOT, "*.jsx"))):
        n = os.path.basename(p)
        lines = sum(1 for _ in open(p, encoding="utf-8", errors="replace"))
        first, defs = (py_entry(p) if n.endswith(".py") else js_entry(p))
        out.append(f"## {n} ({lines} lines)")
        if first:
            out.append(first)
        if defs:
            out.append("`" + ", ".join(f"{name}@{ln}" for ln, name in defs[:400]) + "`")
        out.append("")
    open(os.path.join(ROOT, "docs", "script_index.md"), "w").write("\n".join(out))
    print("wrote docs/script_index.md")


if __name__ == "__main__":
    main()
