#!/usr/bin/env python3
"""Generate STATE.md and state.json from disk (ground truth). Usage: python tools/state.py [--json-only]"""
import csv, hashlib, json, os, re, subprocess, sys, datetime as dt

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
P = lambda *a: os.path.join(ROOT, *a)


def md5(path):
    h = hashlib.md5()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def changelog_head():
    p = P("CHANGELOG.md")
    if not os.path.exists(p):
        return None
    with open(p, encoding="utf-8") as f:
        for line in f:
            if re.match(r"^#{1,3}\s*M\d+", line):
                return line.strip()[:200]
    return None


def master_info():
    p = P("drive_master.csv")
    if not os.path.exists(p):
        return None
    with open(p, newline="", encoding="utf-8") as f:
        r = csv.reader(f)
        header = next(r)
        n = sum(1 for _ in r)
    return {"rows": n, "cols": len(header), "md5": md5(p), "bytes": os.path.getsize(p)}


def arrays_info():
    p = P("summary_arrays.json")
    if not os.path.exists(p):
        return None
    d = json.load(open(p, encoding="utf-8"))
    meta = d.get("meta", {}) if isinstance(d, dict) else {}
    return {"top_level_keys": len(d), "meta_totalDrives": meta.get("totalDrives"),
            "meta_dateRange": meta.get("dateRange"), "md5": md5(p)}


def raw_info():
    rd = os.environ.get("XT_RAW_DIR") or (P("raw") if os.path.isdir(P("raw")) else ROOT)
    n = sum(1 for f in os.listdir(rd) if f.lower().endswith(".csv")) if os.path.isdir(rd) else 0
    man = None
    if os.path.exists(P("raw_manifest.json")):
        m = json.load(open(P("raw_manifest.json"), encoding="utf-8"))
        man = {"snapshotId": m.get("snapshotId"), "roles": m.get("roles"), "integrity_clean": (m.get("integrity") or {}).get("clean")}
    return {"raw_dir": rd, "csv_files_on_disk": n, "manifest": man}


def git_info():
    try:
        h = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, capture_output=True, text=True).stdout.strip()
        dirty = bool(subprocess.run(["git", "status", "--porcelain"], cwd=ROOT, capture_output=True, text=True).stdout.strip())
        return {"head": h or None, "dirty": dirty}
    except Exception:
        return None


def main():
    s = {"generated_utc": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
         "changelog_head": changelog_head(), "drive_master": master_info(), "summary_arrays": arrays_info(),
         "raw": raw_info(), "git": git_info(), "python": sys.version.split()[0]}
    json.dump(s, open(P("state.json"), "w"), indent=1)
    if "--json-only" in sys.argv:
        print(json.dumps(s, indent=1)); return
    dmi, ai = s["drive_master"] or {}, s["summary_arrays"] or {}
    md = ["# STATE (generated by tools/state.py - do not hand-edit)", "",
          f"- Generated: {s['generated_utc']}",
          f"- CHANGELOG head: {s['changelog_head']}",
          f"- drive_master.csv: {dmi.get('rows')} rows x {dmi.get('cols')} cols, MD5 `{dmi.get('md5')}`",
          f"- summary_arrays.json: {ai.get('top_level_keys')} top-level keys, meta.totalDrives={ai.get('meta_totalDrives')}, dateRange={ai.get('meta_dateRange')}",
          f"- Raw CSV files on disk ({s['raw']['raw_dir']}): {s['raw']['csv_files_on_disk']}; manifest: {s['raw']['manifest']}",
          f"- Git: {s['git']}", ""]
    open(P("STATE.md"), "w").write("\n".join(md))
    print("\n".join(md))


if __name__ == "__main__":
    main()
